name: Build .NET Framework App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore YourSolution.sln

      - name: Build solution
        run: msbuild YourSolution.sln /p:Configuration=Release

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **\bin\Release\
